const MONGO_URI = ''; //REPLACE WITH YOUR MONGODB CONNECTION STRING
const port = 3000; //REPLACE WITH PORT NUMBER FOR SERVER
const ip = ''; // REPLACE WITH YOUR IP ADDRESS

module.exports = {
    MONGO_URI,
    port,
};